### ISSUE TITLE
How to add active class in "cloud9-item"

### ISSUE THREAD

**Issue by cred-chirag** [specious/cloud9carousel#15]
i want to add active class which is show in  middle.  like current item

**Comment by specious** [comment]
There's not currently explicit support for that, but I think the [onRendered()](https://github.com/specious/cloud9carousel/blob/cb3076cbc8037ea5014abdc4195c43aeeee392fb/jquery.cloud9carousel.js#L187) hook should allow you enough wiggle room to implement what you're thinking.

When you set up your carousel:
```js
showcase.Cloud9Carousel({
  // ...
  onRendered: function(carousel) {
    for (i = 0; i < carousel.items.length; i++) {
      // You can manipulate items directly
      console.log(carousel.items[i])
    }
  }
})
```
If you get it working, please consider sharing your solution here.

**Comment by killexx** [comment]
Does anyone made it to work?
I try this:
`onRendered: function(carousel) {`
`var index = carousel.nearestIndex();`
`var item = carousel.items[index];`
`$(item).addClass('active');`
`}`
But nothing happens..

**Comment by specious** [comment]
@killexx, try:

```js
$(carousel.items[index].element).addClass('active');
```

**Comment by killexx** [comment]
@specious , Thank you. That works.

**Comment by specious** [comment]
Due to popular demand, as 2.2.0 (f30ad2f2bd9a750ab777660c5aebfd4abec81298), setting the `frontItemClass` property on the carousel [automatically tags the frontmost item](https://github.com/specious/cloud9carousel/commit/f30ad2f2bd9a750ab777660c5aebfd4abec81298#diff-af44906d52f0de98d63fafcd2d81b614R191) with a classname of your choice.

Live [demo](http://jsbin.com/zoyered/edit?html,output) on JSBin.

**Comment by wasimgit** [comment]
onRendered: function(carousel) {
            var index = carousel.nearestIndex();
            $(carousel.items[index].element).addClass('active');
        },
To get the active class to the nearest item
